/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentexam;


import javax.swing.JFrame;

/**
 *
 * @author M Ahmad Tanha
 */
public class StudentExam extends javax.swing.JFrame {

    /**
     * Creates new form StudentExam
     */
    public static int flag=0;
    public StudentExam() {
        initComponents();
        setTitle("Student Exam");
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentMenuBar1 = new javax.swing.JMenuBar();
        examMenu = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();
        changePassword = new javax.swing.JMenuItem();
        logOut = new javax.swing.JMenuItem();
        exitMenu = new javax.swing.JMenuItem();
        studentMenu = new javax.swing.JMenu();
        studentInfo = new javax.swing.JMenuItem();
        studentAdd = new javax.swing.JMenuItem();
        scoreMenu = new javax.swing.JMenu();
        updateMenu = new javax.swing.JMenuItem();
        addMarkMenu = new javax.swing.JMenuItem();
        teacherMenu = new javax.swing.JMenu();
        teacherInfo = new javax.swing.JMenuItem();
        addTeacher = new javax.swing.JMenuItem();
        deleteTeacher = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentexam/20833.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(3600, 2200));
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 2370, 810);

        studentMenuBar1.setBorder(null);
        studentMenuBar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentMenuBar1FocusGained(evt);
            }
        });

        examMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        examMenu.setText("  Exam  ");
        examMenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        examMenu.setMargin(new java.awt.Insets(30, 30, 30, 30));

        loginMenu.setText("Log In");
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        examMenu.add(loginMenu);

        changePassword.setText("Change Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });
        examMenu.add(changePassword);

        logOut.setText("Log Out");
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        examMenu.add(logOut);

        exitMenu.setText(" Exit");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        examMenu.add(exitMenu);

        studentMenuBar1.add(examMenu);

        studentMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        studentMenu.setText("student  ");
        studentMenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        studentInfo.setText("Student Information");
        studentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentInfoActionPerformed(evt);
            }
        });
        studentMenu.add(studentInfo);

        studentAdd.setText("Add Student");
        studentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAddActionPerformed(evt);
            }
        });
        studentMenu.add(studentAdd);

        studentMenuBar1.add(studentMenu);

        scoreMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scoreMenu.setText("Score  ");

        updateMenu.setText("Update Marks");
        scoreMenu.add(updateMenu);

        addMarkMenu.setText("Add Marks");
        addMarkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMarkMenuActionPerformed(evt);
            }
        });
        scoreMenu.add(addMarkMenu);

        studentMenuBar1.add(scoreMenu);

        teacherMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        teacherMenu.setText("teacher  ");
        teacherMenu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        teacherInfo.setText("Teacher information");
        teacherInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherInfoActionPerformed(evt);
            }
        });
        teacherMenu.add(teacherInfo);

        addTeacher.setText("Add Teacher");
        addTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherActionPerformed(evt);
            }
        });
        teacherMenu.add(addTeacher);

        deleteTeacher.setText("Delete Teacher");
        deleteTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeacherActionPerformed(evt);
            }
        });
        teacherMenu.add(deleteTeacher);

        studentMenuBar1.add(teacherMenu);

        setJMenuBar(studentMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2383, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
            new Login().setVisible(true);
    }//GEN-LAST:event_loginMenuActionPerformed

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        new ChangePassword().setVisible(true);
    }//GEN-LAST:event_changePasswordActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void studentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentInfoActionPerformed
        new StudentInfo().setVisible(true);
    }//GEN-LAST:event_studentInfoActionPerformed

    private void studentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAddActionPerformed
        new AddStudent().setVisible(true);
    }//GEN-LAST:event_studentAddActionPerformed

    private void addMarkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMarkMenuActionPerformed
        new AddMarks().setVisible(true);
    }//GEN-LAST:event_addMarkMenuActionPerformed

    private void teacherInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherInfoActionPerformed
        new TeacherInfo().setVisible(true);
    }//GEN-LAST:event_teacherInfoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        hide();
        new Login().setVisible(true);
        
        
    }//GEN-LAST:event_formWindowOpened

    private void addTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherActionPerformed
       new AddTeacher().setVisible(true);
    }//GEN-LAST:event_addTeacherActionPerformed

    private void deleteTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeacherActionPerformed
        new DeleteTeacher().setVisible(true);
    }//GEN-LAST:event_deleteTeacherActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        new Login().setVisible(true);
        flag=0;
        hide();
    }//GEN-LAST:event_logOutActionPerformed

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        // TODO add your handling code here:
        if(flag==0){
         hide();
        
        }
        else if(flag==1){
            view();
            
        }
        
        
    }//GEN-LAST:event_jLabel1FocusGained

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        jLabel1FocusGained(null);
    }//GEN-LAST:event_jPanel1FocusGained

    private void studentMenuBar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentMenuBar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_studentMenuBar1FocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        jLabel1FocusGained(null);
    }//GEN-LAST:event_formFocusGained
   public void view(){
       scoreMenu.setEnabled(true);
       studentMenu.setEnabled(true);
       teacherMenu.setEnabled(true);
       
       logOut.setEnabled(true);
       changePassword.setEnabled(true);
       loginMenu.setEnabled(false);
       
    }
    public void hide(){
       scoreMenu.setEnabled(false);
       studentMenu.setEnabled(false);
       teacherMenu.setEnabled(false);
       
       logOut.setEnabled(false);
      changePassword.setEnabled(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentExam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentExam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addMarkMenu;
    private javax.swing.JMenuItem addTeacher;
    private javax.swing.JMenuItem changePassword;
    private javax.swing.JMenuItem deleteTeacher;
    private javax.swing.JMenu examMenu;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logOut;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenu scoreMenu;
    private javax.swing.JMenuItem studentAdd;
    private javax.swing.JMenuItem studentInfo;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JMenuBar studentMenuBar1;
    private javax.swing.JMenuItem teacherInfo;
    private javax.swing.JMenu teacherMenu;
    private javax.swing.JMenuItem updateMenu;
    // End of variables declaration//GEN-END:variables
}
